# Generated by Django 3.2.15 on 2022-11-20 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_username', models.TextField()),
                ('pickup_username', models.TextField()),
                ('device_id', models.TextField()),
                ('cabinet_no', models.IntegerField()),
                ('moment', models.DateTimeField(default=datetime.datetime.now)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
    ]
